#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$(dirname "${BASH_SOURCE[0]}")/util.sh"
# shellcheck disable=SC1091
source "/usr/local/bin/docker-entrypoint.sh"

: "${PGDATA:?PGDATA is not set. Abort post-upgrade as the script needs the environment variable.}"

# The lock file lives outside the volume because prepareForRestore cleans up the volume root.
POST_UPGRADE_LOCK_FILE="${POST_UPGRADE_LOCK_FILE:-/tmp/post-upgrade.lock}"

# acquirePostUpgradeLock prevents a second post-upgrade from interfering with a running one.
# The lock is released automatically when the process ends.
function acquirePostUpgradeLock() {
  exec 9>"${POST_UPGRADE_LOCK_FILE}"
  if ! flock -n 9; then
    echo "ERROR: Another post-upgrade is still running; aborting." >&2
    exit 1
  fi
}

# rotateSuperuserPassword replaces the superuser password once, because it may have been generated by
# a doguctl older than v0.12.2 which used math/rand instead of crypto/rand. Affected values cannot be
# told apart from safe ones, so the rotation is unconditional and guarded by a config marker only.
function rotateSuperuserPassword() {
  local alreadyRotated
  alreadyRotated=$(doguctl config --default "false" "password_rotated")

  if [[ "${alreadyRotated}" == "true" ]]; then
    echo "Superuser password has already been rotated; skipping"
    return 0
  fi

  echo "Rotating superuser password..."

  local postgresUser
  postgresUser=$(doguctl config --default "postgres" user)

  local newPassword
  newPassword=$(doguctl random)

  # The config is written first: the new password must never exist in the database alone.
  doguctl config --encrypted password "${newPassword}"

  psql \
    --variable=ON_ERROR_STOP=1 \
    --username="${postgresUser}" \
    --command="ALTER USER \"${postgresUser}\" WITH PASSWORD '${newPassword}';"

  # The marker is written last, so an aborted rotation is retried on the next upgrade.
  doguctl config "password_rotated" "true"

  echo "Superuser password rotated"
}

function startPostgresql() {
  echo "starting postgresql temporary"
  docker_temp_server_start postgres
}

function stopPostgresql() {
  echo "stopping temporary postgresql"
  docker_temp_server_stop
}

# initDatabase creates a new, empty cluster in PGDATA with the functions of the official entrypoint.
# The superuser password is taken from the dogu config.
function initDatabase() {
  echo "Initializing new database in ${PGDATA}..."

  POSTGRES_PASSWORD=$(doguctl config -e password)
  export POSTGRES_PASSWORD

  # Internal functions of the upstream /usr/local/bin/docker-entrypoint.sh, same order as in its _main.
  docker_setup_env
  docker_verify_minimum_env
  docker_init_database_dir
  pg_setup_hba_conf postgres
}

function restoreBackup() {
  "$(dirname "${BASH_SOURCE[0]}")/restore.sh"
}

function runMigrations() {
  #run migrations manually
  for script in /docker-entrypoint-initdb.d/*.sh; do
    echo "Manually executing $script..."
    "$script"
  done
}

# New PostgreSQL version requires completely empty folder
function prepareForRestore() {
  echo "Preparing storage for restore..."

  # Handle databases from old version where data is stored within /var/lib/postgresql
  if [[ -s "/var/lib/postgresql/PG_VERSION" ]]; then
    echo "Found legacy database in volume root, cleaning up..."

    # Protected folders:
    # - backup: holds the backup to be restored
    # - data: is the volume mount of the postgres image 14
    # - 14, 15, ect. : Database folder for the upgrade
    cd /var/lib/postgresql/
    find . -maxdepth 1 ! -name '.' ! -name 'backup' ! -name 'data' ! -name "${PG_MAJOR%%.*}" -exec rm -rf {} +
  fi

  if [[ -d "${PGDATA}" ]]; then
    echo "Cleaning target directory ${PGDATA}..."
    find "${PGDATA}" -mindepth 1 -delete
  fi

  mkdir -p "${PGDATA}"
}

function runPostUpgrade() {
    FROM_VERSION="${1}"
    TO_VERSION="${2}"

    echo "Running post upgrade from version ${FROM_VERSION} to ${TO_VERSION}"

    if [[ "${FROM_VERSION}" = "${TO_VERSION}" ]]; then
      echo "FROM and TO versions are the same; Exiting..."
      doguctl config --rm "local_state"
      exit 0
    fi

    local user; user=$(doguctl config -d "postgres" user)
    export PGUSER="${user}"

    # initdb and pg_ctl refuse to run as root, so the script restarts itself as postgres like the official entrypoint does.
    # Only the chown needs root: files of the old image may still belong to another UID.
    if [ "$(id -u)" = '0' ]; then
      # taken once before the restart, the postgres run inherits the lock
      acquirePostUpgradeLock

      #fix permissions in volume root
      chown -R "${user}" /var/lib/postgresql/

      exec gosu postgres "${BASH_SOURCE[0]}" "$@"
    fi

    local backupFile; backupFile=$(doguctl config -d "empty" "migration_backup_path")

    # The restore must be completed within this script, because the dogu operator restarts the pod as soon as it has finished.
    # local_state is removed only at the very end, so startup.sh waits until the restore is done.
    # If a run is aborted, the flag stays set and the next run starts over with an empty PGDATA.
    if [[ "${backupFile}" != "empty" ]] ; then
      if [[ ! -f "${backupFile}" ]]; then
        echo "ERROR: Backup file ${backupFile} not found on disk! Keep the existing data and abort post-upgrade." >&2
        exit 1
      fi

      echo "backup found in config, prepare for restore..."
      prepareForRestore
      initDatabase
    elif [[ ! -s "${PGDATA}/PG_VERSION" ]]; then
      echo "PostgreSQL does not seem to be initialized, skip post upgrade..."
      doguctl config --rm "local_state"
      exit 0
    fi

    startPostgresql
    if [[ "${backupFile}" != "empty" ]] ; then
      restoreBackup
    fi
    rotateSuperuserPassword
    runMigrations
    stopPostgresql

    doguctl config --rm "local_state"
    echo "Postgresql post-upgrade done"
}

# make the script only run when executed, not when sourced from bats tests
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    runPostUpgrade "$@"
fi
